version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    # restart: always
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
    stdin_open: true
    tty: true
# networks:
#   networks1:
#     name: 'innoscripta-network'
#     external: true
